#import "CAReportViewController.h"
#import "CALogStore.h"
#import <Preferences/Preferences.h>
@implementation CAReportViewController { NSArray *_items; NSString *_category; }
- (instancetype)initWithSpecifier:(PSSpecifier *)specifier { self=[super initWithStyle:UITableViewStyleInsetGrouped]; if (self) { _specifier=specifier; } return self; }
- (void)viewDidLoad { [super viewDidLoad]; _category=self.specifier.properties[@"category"] ?: @"其他"; self.title=_category; self.tableView.rowHeight=76; [self reload]; self.navigationItem.rightBarButtonItem=[[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemRefresh target:self action:@selector(reload)]; }
- (void)reload { _items=[[CALogStore sharedStore] reportsForCategory:_category]; [self.tableView reloadData]; }
- (NSInteger)tableView:(UITableView *)t numberOfRowsInSection:(NSInteger)s { return _items.count; }
- (UITableViewCell *)tableView:(UITableView *)t cellForRowAtIndexPath:(NSIndexPath *)i { UITableViewCell *c=[t dequeueReusableCellWithIdentifier:@"r"]; if (!c) c=[[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:@"r"]; NSDictionary *r=_items[i.row]; c.textLabel.text=r[@"procName"] ?: r[@"app_name"] ?: r[@"fileName"]; c.detailTextLabel.text=[NSString stringWithFormat:@"%@ · %@\n%@",r[@"timestamp"] ?: @"时间未知",r[@"bug_type"] ?: _category,r[@"diagnosis"] ?: @""]; c.detailTextLabel.numberOfLines=2; c.accessoryType=UITableViewCellAccessoryDisclosureIndicator; return c; }
- (void)tableView:(UITableView *)t didSelectRowAtIndexPath:(NSIndexPath *)i { NSDictionary *r=_items[i.row]; NSString *text=[NSString stringWithFormat:@"%@\n\n%@\n\n%@",r[@"fileName"] ?: @"日志",r[@"diagnosis"] ?: @"",r[@"path"] ?: @""]; UIAlertController *a=[UIAlertController alertControllerWithTitle:r[@"procName"] ?: r[@"app_name"] message:text preferredStyle:UIAlertControllerStyleAlert]; [a addAction:[UIAlertAction actionWithTitle:@"关闭" style:UIAlertActionStyleCancel handler:nil]]; [a addAction:[UIAlertAction actionWithTitle:@"分享原始日志" style:UIAlertActionStyleDefault handler:^(UIAlertAction *x){ NSString *p=r[@"path"]; if (!p) return; UIActivityViewController *v=[[UIActivityViewController alloc] initWithActivityItems:@[[NSURL fileURLWithPath:p]] applicationActivities:nil]; [self presentViewController:v animated:YES completion:nil]; }]]; [self presentViewController:a animated:YES completion:nil]; [t deselectRowAtIndexPath:i animated:YES]; }
@end
